using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CustomerPortal.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;
using Newtonsoft.Json.Linq;
using Microsoft.Extensions.Configuration;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;

namespace CustomerPortal.Controllers
{
    public class HomeController : Controller
    {

        private IConfiguration _configuration;


        /// <summary>
        /// Injecting the IConfiguration in the Controller
        /// to access the urls from the appsettings.json
        /// </summary>
        /// <param name="configuration"></param>
        public HomeController(IConfiguration configuration)
        {
            _configuration = configuration;
        }


        /// <summary>
        /// The default method of home controller. it redirects to the login page
        /// 
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return RedirectToAction("Login");
        }

        /// <summary>
        /// the Login page is generated by this method.
        /// </summary>
        /// <returns></returns>
        public IActionResult Login()
        {
            return View();
        }

        /// <summary>
        /// The login data enterd by the user is sent to this. It validates that data
        /// by sending it to the authentication. If that api returns a token, that means the user is valid. If it does not, then it means that the user 
        /// is not valid.
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Login(Users user)
        {
            var connection = _configuration["AuthenticationToken"];
            string token = GetToken(connection, user);

            if (token != null)
            {
                HttpContext.Session.SetString("JWTtoken", token);
                HttpContext.Session.SetString("Id", user.PortFolioID.ToString());
                return RedirectToAction("Index", "PortFolio");
            }
            else
            {
                ModelState.Clear();
                ModelState.AddModelError(string.Empty, "Username or Password is Incorrect");
                ViewBag.invalid = "UserId or Password invalid";
                return View();
            }
        }


        /// <summary>
        /// This method calls the Authentication api. 
        /// </summary>
        /// <param name="url"></param>
        /// <param name="user"></param>
        /// <returns></returns>
        static string GetToken(string url, Users user)
        {
            var json = JsonConvert.SerializeObject(user);
            var data = new StringContent(json, Encoding.UTF8, "application/json");

            using (var client = new HttpClient())
            {
                var response = client.PostAsync(url, data).Result;
                string name = response.Content.ReadAsStringAsync().Result;
                dynamic details = JObject.Parse(name);
                return details.tokenString;
            }
        }
    }
}
